name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [api, web]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install
        run: cd ${{ matrix.project }} && npm ci
      - name: Lint
        run: cd ${{ matrix.project }} && npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [api, web]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install
        run: cd ${{ matrix.project }} && npm ci
      - name: Test
        run: cd ${{ matrix.project }} && npm test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    strategy:
      matrix:
        project: [api, web]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install
        run: cd ${{ matrix.project }} && npm ci
      - name: Build
        run: cd ${{ matrix.project }} && npm run build
